# Importing Libraries

In [509]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Loading data

In [510]:
data = pd.read_csv("covid.csv")

In [511]:
data.head(10)

,id,sex,patient_type,entry_date,date_symptoms,date_died,intubed,pneumonia,age,pregnancy,...,inmsupr,hypertension,other_disease,cardiovascular,obesity,renal_chronic,tobacco,contact_other_covid,covid_res,icu
0,16169f,2,1,04-05-2020,02-05-2020,9999-99-99,97,2,27,97,...,2,2,2,2,2,2,2,2,1,97
1,1009bf,2,1,19-03-2020,17-03-2020,9999-99-99,97,2,24,97,...,2,2,2,2,2,2,2,99,1,97
2,167386,1,2,06-04-2020,01-04-2020,9999-99-99,2,2,54,2,...,2,2,2,2,1,2,2,99,1,2
3,0b5948,2,2,17-04-2020,10-04-2020,9999-99-99,2,1,30,97,...,2,2,2,2,2,2,2,99,1,2
4,0d01b5,1,2,13-04-2020,13-04-2020,22-04-2020,2,2,60,2,...,2,1,2,1,2,2,2,99,1,2
5,1beec8,2,2,16-04-2020,16-04-2020,29-04-2020,2,1,47,97,...,2,2,2,2,2,2,2,99,1,1
6,1.75E+56,2,2,22-04-2020,13-04-2020,9999-99-99,2,2,63,97,...,2,1,2,2,2,2,2,99,1,2
7,0ce1f5,1,1,21-05-2020,18-05-2020,9999-99-99,97,2,56,2,...,2,1,2,2,2,1,1,1,1,97
8,12b57a,1,1,22-04-2020,18-04-2020,9999-99-99,97,2,41,2,...,2,2,2,2,2,2,2,99,1,97
9,006b91,1,2,23-04-2020,18-04-2020,9999-99-99,1,1,39,2,...,2,2,2,2,1,2,2,99,1,2

In [512]:
data.columns

Index(['id', 'sex', 'patient_type', 'entry_date', 'date_symptoms', 'date_died',
       'intubed', 'pneumonia', 'age', 'pregnancy', 'diabetes', 'copd',
       'asthma', 'inmsupr', 'hypertension', 'other_disease', 'cardiovascular',
       'obesity', 'renal_chronic', 'tobacco', 'contact_other_covid',
       'covid_res', 'icu'],
      dtype='object')

In [513]:
data.sample(5)

,id,sex,patient_type,entry_date,date_symptoms,date_died,intubed,pneumonia,age,pregnancy,...,inmsupr,hypertension,other_disease,cardiovascular,obesity,renal_chronic,tobacco,contact_other_covid,covid_res,icu
360099,07c1d1,2,1,28-05-2020,27-05-2020,9999-99-99,97,2,25,97,...,2,2,2,2,2,2,2,1,2,97
288027,0862a5,1,1,26-06-2020,22-06-2020,9999-99-99,97,2,31,2,...,2,2,2,2,2,2,2,1,2,97
502739,18e4ce,2,2,09-06-2020,07-06-2020,9999-99-99,2,1,38,97,...,2,2,2,2,1,2,2,99,3,2
440407,14b200,2,1,23-04-2020,17-04-2020,9999-99-99,97,2,62,97,...,2,1,2,2,2,2,2,2,2,97
346167,08e7bd,1,1,26-05-2020,24-05-2020,9999-99-99,97,2,27,2,...,2,2,2,2,2,2,1,99,2,97

In [514]:
data.iloc[1219]

id                         1719d0
sex                             1
patient_type                    1
entry_date             06-05-2020
date_symptoms          01-05-2020
date_died              16-05-2020
intubed                        97
pneumonia                       2
age                            71
pregnancy                       2
diabetes                        2
copd                            2
asthma                          2
inmsupr                         2
hypertension                    2
other_disease                   2
cardiovascular                  2
obesity                         2
renal_chronic                   2
tobacco                         2
contact_other_covid            99
covid_res                       1
icu                            97
Name: 1219, dtype: object

# Preprocessing data

In [515]:
dead = data['date_died'].values
# print(dead.shape)
dead = np.where(dead == '9999-99-99', 0, 1)
# print(dead.shape)

In [516]:
data_02 = data.copy()
data_02['dead'] = dead
data_02.head()

,id,sex,patient_type,entry_date,date_symptoms,date_died,intubed,pneumonia,age,pregnancy,...,hypertension,other_disease,cardiovascular,obesity,renal_chronic,tobacco,contact_other_covid,covid_res,icu,dead
0,16169f,2,1,04-05-2020,02-05-2020,9999-99-99,97,2,27,97,...,2,2,2,2,2,2,2,1,97,0
1,1009bf,2,1,19-03-2020,17-03-2020,9999-99-99,97,2,24,97,...,2,2,2,2,2,2,99,1,97,0
2,167386,1,2,06-04-2020,01-04-2020,9999-99-99,2,2,54,2,...,2,2,2,1,2,2,99,1,2,0
3,0b5948,2,2,17-04-2020,10-04-2020,9999-99-99,2,1,30,97,...,2,2,2,2,2,2,99,1,2,0
4,0d01b5,1,2,13-04-2020,13-04-2020,22-04-2020,2,2,60,2,...,1,2,1,2,2,2,99,1,2,1

In [517]:
data_02.columns.size
features = data_02.columns[1:-1]
features

Index(['sex', 'patient_type', 'entry_date', 'date_symptoms', 'date_died',
       'intubed', 'pneumonia', 'age', 'pregnancy', 'diabetes', 'copd',
       'asthma', 'inmsupr', 'hypertension', 'other_disease', 'cardiovascular',
       'obesity', 'renal_chronic', 'tobacco', 'contact_other_covid',
       'covid_res', 'icu'],
      dtype='object')

In [518]:
data_02.head()

,id,sex,patient_type,entry_date,date_symptoms,date_died,intubed,pneumonia,age,pregnancy,...,hypertension,other_disease,cardiovascular,obesity,renal_chronic,tobacco,contact_other_covid,covid_res,icu,dead
0,16169f,2,1,04-05-2020,02-05-2020,9999-99-99,97,2,27,97,...,2,2,2,2,2,2,2,1,97,0
1,1009bf,2,1,19-03-2020,17-03-2020,9999-99-99,97,2,24,97,...,2,2,2,2,2,2,99,1,97,0
2,167386,1,2,06-04-2020,01-04-2020,9999-99-99,2,2,54,2,...,2,2,2,1,2,2,99,1,2,0
3,0b5948,2,2,17-04-2020,10-04-2020,9999-99-99,2,1,30,97,...,2,2,2,2,2,2,99,1,2,0
4,0d01b5,1,2,13-04-2020,13-04-2020,22-04-2020,2,2,60,2,...,1,2,1,2,2,2,99,1,2,1

In [519]:
for feature in features:
    print(f'{feature} unique values: {data_02[feature].unique()}\n-------------------------------------------')

sex unique values: [2 1]
-------------------------------------------
patient_type unique values: [1 2]
-------------------------------------------
entry_date unique values: ['04-05-2020' '19-03-2020' '06-04-2020' '17-04-2020' '13-04-2020'
 '16-04-2020' '22-04-2020' '21-05-2020' '23-04-2020' '29-04-2020'
 '02-05-2020' '25-05-2020' '07-06-2020' '20-06-2020' '24-06-2020'
 '30-04-2020' '05-05-2020' '12-05-2020' '19-04-2020' '02-06-2020'
 '25-04-2020' '15-05-2020' '27-04-2020' '01-04-2020' '22-06-2020'
 '21-04-2020' '24-04-2020' '20-04-2020' '28-04-2020' '26-04-2020'
 '19-06-2020' '31-03-2020' '03-04-2020' '14-04-2020' '12-04-2020'
 '29-03-2020' '06-05-2020' '11-06-2020' '10-06-2020' '02-04-2020'
 '19-05-2020' '05-06-2020' '17-06-2020' '10-04-2020' '03-05-2020'
 '16-06-2020' '30-03-2020' '15-04-2020' '08-06-2020' '15-06-2020'
 '25-03-2020' '25-06-2020' '08-04-2020' '27-05-2020' '20-05-2020'
 '01-06-2020' '18-06-2020' '07-05-2020' '08-05-2020' '29-05-2020'
 '07-04-2020' '11-04-2020' '23-03-2020' '11-05-2020' '18-04-2020'
 '17-05-2020' '22-05-2020' '05-04-2020' '23-06-2020' '24-03-2020'
 '12-06-2020' '30-05-2020' '13-05-2020' '26-03-2020' '16-05-2020'
 '04-04-2020' '20-03-2020' '17-03-2020' '01-05-2020' '31-05-2020'
 '21-06-2020' '22-03-2020' '09-06-2020' '14-06-2020' '10-05-2020'
 '14-05-2020' '04-06-2020' '06-06-2020' '18-05-2020' '13-06-2020'
 '09-04-2020' '09-05-2020' '28-05-2020' '03-06-2020' '26-05-2020'
 '18-03-2020' '24-05-2020' '28-03-2020' '27-03-2020' '26-06-2020'
 '21-03-2020' '23-05-2020' '13-01-2020' '28-06-2020' '27-06-2020'
 '12-03-2020' '14-03-2020' '29-06-2020' '27-02-2020' '16-03-2020'
 '11-03-2020' '13-03-2020' '15-03-2020' '04-03-2020' '07-03-2020'
 '28-02-2020' '02-03-2020' '12-02-2020' '10-03-2020' '14-01-2020'
 '08-03-2020' '09-03-2020' '28-01-2020' '05-03-2020' '29-02-2020'
 '29-01-2020' '05-02-2020' '24-02-2020' '12-01-2020' '03-03-2020'
 '27-01-2020' '11-02-2020' '01-03-2020' '30-01-2020' '08-01-2020'
 '15-01-2020' '24-01-2020' '06-03-2020' '22-01-2020' '23-02-2020'
 '10-02-2020' '07-02-2020' '09-02-2020' '26-02-2020' '26-01-2020'
 '13-02-2020' '23-01-2020' '02-02-2020' '04-01-2020' '25-02-2020'
 '06-01-2020' '20-01-2020' '17-01-2020' '14-02-2020' '02-01-2020'
 '09-01-2020' '06-02-2020' '16-02-2020' '10-01-2020' '16-01-2020'
 '25-01-2020' '17-02-2020' '31-01-2020' '18-02-2020' '20-02-2020'
 '22-02-2020' '18-01-2020' '19-01-2020' '07-01-2020' '21-01-2020'
 '03-02-2020' '21-02-2020' '04-02-2020' '08-02-2020' '19-02-2020'
 '03-01-2020' '01-02-2020' '15-02-2020' '11-01-2020' '01-01-2020'
 '05-01-2020']
-------------------------------------------
date_symptoms unique values: ['02-05-2020' '17-03-2020' '01-04-2020' '10-04-2020' '13-04-2020'
 '16-04-2020' '18-05-2020' '18-04-2020' '22-04-2020' '27-04-2020'
 '23-05-2020' '04-06-2020' '16-06-2020' '15-06-2020' '20-04-2020'
 '01-05-2020' '19-04-2020' '02-06-2020' '29-04-2020' '06-05-2020'
 '18-06-2020' '25-04-2020' '28-03-2020' '14-05-2020' '17-06-2020'
 '15-04-2020' '21-04-2020' '09-04-2020' '27-05-2020' '23-04-2020'
 '27-03-2020' '03-04-2020' '14-04-2020' '07-04-2020' '19-03-2020'
 '12-04-2020' '03-05-2020' '08-06-2020' '26-03-2020' '10-06-2020'
 '24-04-2020' '31-05-2020' '06-04-2020' '11-04-2020' '12-06-2020'
 '05-04-2020' '14-06-2020' '12-03-2020' '07-06-2020' '08-04-2020'
 '18-03-2020' '20-06-2020' '30-03-2020' '17-04-2020' '30-04-2020'
 '20-03-2020' '13-05-2020' '01-06-2020' '05-05-2020' '02-04-2020'
 '06-06-2020' '25-05-2020' '26-05-2020' '08-05-2020' '15-03-2020'
 '26-04-2020' '09-06-2020' '19-05-2020' '09-05-2020' '12-05-2020'
 '17-05-2020' '16-03-2020' '04-04-2020' '04-05-2020' '22-05-2020'
 '21-06-2020' '24-03-2020' '07-05-2020' '29-03-2020' '30-05-2020'
 '13-03-2020' '20-05-2020' '11-06-2020' '24-05-2020' '22-03-2020'
 '21-03-2020' '23-06-2020' '16-05-2020' '03-06-2020' '05-06-2020'
 '28-04-2020' '31-03-2020' '28-05-2020' '10-05-2020' '11-05-2020'
 '23-03-2020' '15-05-2020' '21-05-2020' '13-06-2020' '19-06-2020'
 '22-06-2020' '29-05-2020' '11-03-2020' '25-03-2020' '26-06-2020'
 '13-01-2020' '24-06-2020' '14-03-2020' '25-06-2020' '02-03-2020'
 '27-06-2020' '23-02-2020' '01-03-2020' '10-03-2020' '04-03-2020'
 '05-03-2020' '09-03-2020' '07-03-2020' '22-02-2020' '08-03-2020'
 '28-02-2020' '29-02-2020' '19-02-2020' '03-03-2020' '07-02-2020'
 '06-03-2020' '28-06-2020' '14-01-2020' '28-01-2020' '26-02-2020'
 '06-02-2020' '21-02-2020' '25-02-2020' '29-01-2020' '27-02-2020'
 '17-01-2020' '05-02-2020' '12-01-2020' '21-01-2020' '09-02-2020'
 '30-01-2020' '06-01-2020' '23-01-2020' '19-01-2020' '10-02-2020'
 '04-02-2020' '26-01-2020' '10-01-2020' '22-01-2020' '20-01-2020'
 '12-02-2020' '01-02-2020' '13-02-2020' '04-01-2020' '15-01-2020'
 '05-01-2020' '11-02-2020' '01-01-2020' '09-01-2020' '27-01-2020'
 '25-01-2020' '14-02-2020' '24-01-2020' '17-02-2020' '24-02-2020'
 '16-02-2020' '20-02-2020' '08-02-2020' '16-01-2020' '18-01-2020'
 '03-02-2020' '18-02-2020' '11-01-2020' '07-01-2020' '02-01-2020'
 '08-01-2020' '02-02-2020' '15-02-2020' '31-01-2020' '03-01-2020'
 '29-06-2020']
-------------------------------------------
date_died unique values: ['9999-99-99' '22-04-2020' '29-04-2020' '21-05-2020' '28-04-2020'
 '26-04-2020' '07-04-2020' '13-04-2020' '20-04-2020' '25-04-2020'
 '19-06-2020' '06-04-2020' '15-05-2020' '13-05-2020' '09-06-2020'
 '08-05-2020' '24-04-2020' '03-05-2020' '15-04-2020' '16-04-2020'
 '30-03-2020' '30-04-2020' '14-06-2020' '19-04-2020' '14-05-2020'
 '07-05-2020' '28-03-2020' '16-05-2020' '09-04-2020' '18-05-2020'
 '05-04-2020' '21-04-2020' '01-06-2020' '15-06-2020' '18-04-2020'
 '05-06-2020' '20-05-2020' '09-05-2020' '11-05-2020' '04-05-2020'
 '10-05-2020' '05-05-2020' '23-04-2020' '22-05-2020' '27-04-2020'
 '02-05-2020' '12-05-2020' '21-06-2020' '17-05-2020' '26-05-2020'
 '04-06-2020' '11-06-2020' '06-05-2020' '19-05-2020' '25-05-2020'
 '17-04-2020' '01-04-2020' '29-03-2020' '14-04-2020' '11-04-2020'
 '01-05-2020' '16-06-2020' '26-06-2020' '27-05-2020' '23-05-2020'
 '22-03-2020' '03-06-2020' '03-04-2020' '24-05-2020' '08-04-2020'
 '02-04-2020' '30-05-2020' '31-05-2020' '12-04-2020' '23-06-2020'
 '06-06-2020' '17-06-2020' '28-05-2020' '10-04-2020' '12-06-2020'
 '13-06-2020' '22-06-2020' '29-05-2020' '02-06-2020' '20-06-2020'
 '10-06-2020' '07-06-2020' '18-06-2020' '25-06-2020' '08-06-2020'
 '24-06-2020' '27-06-2020' '28-06-2020' '04-04-2020' '26-03-2020'
 '31-03-2020' '23-03-2020' '29-06-2020' '27-03-2020' '20-03-2020'
 '25-03-2020' '18-03-2020' '24-03-2020' '29-01-2020' '04-03-2020'
 '17-03-2020' '14-01-2020' '23-02-2020' '30-01-2020' '08-02-2020'
 '16-03-2020' '10-02-2020' '09-03-2020' '11-02-2020' '11-03-2020'
 '22-02-2020' '26-02-2020' '09-02-2020' '15-01-2020' '25-02-2020'
 '21-02-2020' '13-02-2020' '13-01-2020' '12-03-2020']
-------------------------------------------
intubed unique values: [97  2  1 99]
-------------------------------------------
pneumonia unique values: [ 2  1 99]
-------------------------------------------
age unique values: [ 27  24  54  30  60  47  63  56  41  39  46  45  28  34  38  49  25  40
  61  31  33  52  83  43  77  37  32  53  42  57  48  59  44  65  73  71
  51  50  35  67  55  78  29  79  36  66  74  58  84  26  80   3  75  68
  87  69  89  76  62  18  23  70  17  72   0  81  64  88  20  15  22  14
  16  86  92  90  82   5   7  11  21  85  95  19   1   4  97  10  93   9
   8  12  13   6  91   2  98  96  94 100 119 101  99 103 114 106 120 105
 102 116 104 118 109 110 117 115 113 108 107 111]
-------------------------------------------
pregnancy unique values: [97  2  1 98]
-------------------------------------------
diabetes unique values: [ 2  1 98]
-------------------------------------------
copd unique values: [ 2  1 98]
-------------------------------------------
asthma unique values: [ 2  1 98]
-------------------------------------------
inmsupr unique values: [ 2  1 98]
-------------------------------------------
hypertension unique values: [ 2  1 98]
-------------------------------------------
other_disease unique values: [ 2  1 98]
-------------------------------------------
cardiovascular unique values: [ 2  1 98]
-------------------------------------------
obesity unique values: [ 2  1 98]
-------------------------------------------
renal_chronic unique values: [ 2  1 98]
-------------------------------------------
tobacco unique values: [ 2  1 98]
-------------------------------------------
contact_other_covid unique values: [ 2 99  1]
-------------------------------------------
covid_res unique values: [1 2 3]
-------------------------------------------
icu unique values: [97  2  1 99]
-------------------------------------------

In [520]:
print(data_02[data_02['covid_res'] == 1].shape)
print(data_02[data_02['covid_res'] == 2].shape)
print(data_02[data_02['covid_res'] == 3].shape)

(220657, 24)
(279035, 24)
(66910, 24)

In [521]:
# the values 97 and 99 are not valid for this column
invalid_intubed = data_02[(data_02['intubed'] != 1) & (data_02['intubed'] != 2)]
display(invalid_intubed.sample(10))
invalid_intubed.shape

,id,sex,patient_type,entry_date,date_symptoms,date_died,intubed,pneumonia,age,pregnancy,...,hypertension,other_disease,cardiovascular,obesity,renal_chronic,tobacco,contact_other_covid,covid_res,icu,dead
428014,169f23,2,1,12-05-2020,02-05-2020,9999-99-99,97,2,53,97,...,2,2,2,2,2,2,1,2,97,0
70378,03db06,1,1,19-06-2020,19-06-2020,9999-99-99,97,2,54,2,...,2,2,2,2,2,2,2,1,97,0
489853,1ab8b8,2,1,25-04-2020,25-04-2020,9999-99-99,97,2,56,97,...,2,2,2,2,2,2,1,2,97,0
15035,09178c,2,1,15-05-2020,12-05-2020,9999-99-99,97,1,62,97,...,2,2,2,2,2,1,2,1,97,0
251820,0b259b,2,1,01-06-2020,31-05-2020,9999-99-99,97,2,25,97,...,2,2,2,1,2,2,99,2,97,0
417929,1ae87e,1,1,11-06-2020,07-06-2020,9999-99-99,97,2,62,2,...,1,2,2,2,2,2,1,2,97,0
358880,07b13c,2,1,05-06-2020,04-06-2020,9999-99-99,97,1,53,97,...,2,2,2,2,2,1,2,2,97,0
565397,15700b,1,1,22-05-2020,16-05-2020,9999-99-99,97,2,83,2,...,1,2,2,1,2,2,99,3,97,0
397215,04f7b6,2,1,05-06-2020,02-06-2020,9999-99-99,97,2,37,97,...,2,2,2,2,2,2,1,2,97,0
450236,0540c6,1,1,19-05-2020,16-05-2020,9999-99-99,97,2,29,2,...,2,2,2,2,2,2,1,2,97,0

(444813, 24)

In [522]:
print(invalid_intubed[invalid_intubed['intubed'] == 97]['patient_type'].unique())
print(invalid_intubed[invalid_intubed['intubed'] == 99]['patient_type'].unique())

[1]
[2]

In [523]:
data_02.loc[:,'intubed'].replace(99, 2, inplace=True)

In [524]:
data_02.intubed.unique()

array([97,  2,  1], dtype=int64)

In [525]:
invalid_intubed = data_02[data_02['intubed'] == 97]
print(invalid_intubed.shape)
invalid_intubed['intubed'].unique()

(444689, 24)

array([97], dtype=int64)

regarding the fact that the miss values of this column in comparison with the whole data is not negligible. So I am going to delete this column

In [526]:
data_02.drop('intubed', axis='columns', inplace=True)

In [527]:
# the value 99 is not valid for this column
invalid_pneumonia = data_02[(data_02['pneumonia'] != 1) & (data_02['pneumonia'] != 2)]
display(invalid_pneumonia.sample(10))
invalid_pneumonia.shape

,id,sex,patient_type,entry_date,date_symptoms,date_died,pneumonia,age,pregnancy,diabetes,...,hypertension,other_disease,cardiovascular,obesity,renal_chronic,tobacco,contact_other_covid,covid_res,icu,dead
296720,1c7b37,1,1,30-03-2020,26-03-2020,9999-99-99,99,22,2,2,...,2,2,2,2,2,2,1,2,97,0
355470,1091db,2,1,05-04-2020,01-04-2020,9999-99-99,99,30,97,2,...,2,1,2,2,2,2,1,2,97,0
83297,1043c3,2,1,08-06-2020,02-06-2020,9999-99-99,99,26,97,2,...,2,2,2,2,2,2,2,1,97,0
348721,0ec473,1,1,02-06-2020,21-05-2020,9999-99-99,99,46,2,2,...,2,2,2,2,2,2,2,2,97,0
404570,zzb8a2,2,2,03-06-2020,01-06-2020,9999-99-99,99,25,97,2,...,2,2,2,2,2,2,1,2,99,0
107211,0aefba,1,1,21-05-2020,18-05-2020,9999-99-99,99,37,2,2,...,2,2,2,2,2,2,99,1,97,0
197082,5.39E+11,2,1,12-03-2020,12-03-2020,9999-99-99,99,40,97,2,...,2,2,2,1,2,2,99,1,97,0
446734,12bed5,1,1,30-03-2020,29-03-2020,9999-99-99,99,26,2,2,...,2,2,2,2,2,2,2,2,97,0
363592,00299b,2,1,13-05-2020,13-05-2020,9999-99-99,99,36,97,2,...,2,2,2,2,2,2,1,2,97,0
454381,zzf49f,1,1,20-05-2020,19-05-2020,9999-99-99,99,63,2,2,...,2,2,2,2,2,2,2,2,97,0

(11, 23)

Number of missing values of this column is small. So I just delete those rows that contain these missing values.

In [528]:
data_02.drop(invalid_pneumonia.index, inplace=True)
data_02['pneumonia'].unique()

array([2, 1], dtype=int64)

In [529]:
# data_02.shape

In [530]:
# the values 97 and 98 are not valid for this column
invalid_pregnancy = data_02[(data_02['pregnancy'] != 1) & (data_02['pregnancy'] != 2)]
display(invalid_pregnancy.sample(10))
invalid_pregnancy.shape

,id,sex,patient_type,entry_date,date_symptoms,date_died,pneumonia,age,pregnancy,diabetes,...,hypertension,other_disease,cardiovascular,obesity,renal_chronic,tobacco,contact_other_covid,covid_res,icu,dead
151021,139a3b,2,1,30-04-2020,14-04-2020,9999-99-99,2,35,97,2,...,2,2,2,2,2,2,99,1,97,0
500272,0fa40d,2,1,25-06-2020,19-06-2020,9999-99-99,2,27,97,2,...,2,2,2,2,2,2,99,3,97,0
465999,1765b1,2,1,01-04-2020,30-03-2020,9999-99-99,2,37,97,2,...,2,2,2,2,2,1,99,2,97,0
398184,071cf5,2,1,11-05-2020,10-05-2020,9999-99-99,2,46,97,2,...,2,2,2,1,2,2,1,2,97,0
272252,0e831b,2,1,02-06-2020,01-06-2020,9999-99-99,2,40,97,2,...,2,1,1,2,2,1,1,2,97,0
186640,12e28a,2,1,10-06-2020,05-06-2020,9999-99-99,2,43,97,2,...,2,2,2,1,2,2,1,1,97,0
493790,18be60,2,2,08-06-2020,08-06-2020,9999-99-99,1,58,97,2,...,2,2,2,2,2,1,99,2,2,0
36426,0e7fec,2,1,15-06-2020,13-06-2020,9999-99-99,2,34,97,2,...,2,2,2,2,2,2,99,1,97,0
171526,1674da,2,1,08-05-2020,04-05-2020,9999-99-99,1,25,97,1,...,2,2,2,1,2,2,1,1,97,0
49294,09477c,2,2,23-05-2020,11-05-2020,9999-99-99,1,44,97,2,...,2,2,2,2,2,2,99,1,2,0

(288693, 23)

In [531]:
print(data_02[data_02['pregnancy'] == 2]['sex'].unique())
print(data_02[data_02['pregnancy'] == 1]['sex'].unique())

[1]
[1]

this means that value 1 in sex column belongs to women. So if in pregnancy column there is an invalid value and its sex feature is 2, then obviously its pregnancy test would result in false.

In [532]:
print(invalid_pregnancy[invalid_pregnancy['pregnancy'] == 97]['sex'].unique())
print(invalid_pregnancy[invalid_pregnancy['pregnancy'] == 98]['sex'].unique())
# invalid_pregnancy[invalid_pregnancy['pregnancy'] == 97]
# invalid_pregnancy.isin({'pregnancy':[97]}).sum()

[2]
[1]

In [533]:
data_02.loc[:, 'pregnancy'].replace(97, 1, inplace=True)
# data_02.isin({'pregnancy':[97]}).sum()
# data_02[data_02['pregnancy'] == 97]

In [534]:
invalid_pregnancy = data_02[data_02['pregnancy'] == 98]
# invalid_pregnancy['pregnancy'].unique()
# print(invalid_pregnancy.shape)
data_02.drop(invalid_pregnancy.index, inplace=True)

In [535]:
# data_02.shape

In [536]:
data_02['pregnancy'].unique()

array([1, 2], dtype=int64)

In [537]:
# the value 98 not valid for this column
invalid_diabetes = data_02[(data_02['diabetes'] != 1) & (data_02['diabetes'] != 2)]
display(invalid_diabetes.sample(10))
invalid_diabetes.shape

,id,sex,patient_type,entry_date,date_symptoms,date_died,pneumonia,age,pregnancy,diabetes,...,hypertension,other_disease,cardiovascular,obesity,renal_chronic,tobacco,contact_other_covid,covid_res,icu,dead
167752,1db3a4,2,1,18-06-2020,15-06-2020,9999-99-99,2,56,1,98,...,98,98,98,98,98,98,1,1,97,0
29775,0ce3de,1,2,20-04-2020,18-04-2020,9999-99-99,2,66,2,98,...,2,2,2,1,2,2,2,1,2,0
419190,0ed4ba,1,1,08-04-2020,05-04-2020,9999-99-99,2,24,2,98,...,98,98,98,98,98,98,1,2,97,0
97426,18a244,2,1,08-06-2020,03-06-2020,9999-99-99,2,39,1,98,...,2,2,2,2,2,2,99,1,97,0
83590,56243,1,2,16-04-2020,10-04-2020,23-04-2020,1,36,1,98,...,98,98,98,1,98,2,1,1,1,1
67870,12eb72,1,1,18-05-2020,18-05-2020,9999-99-99,2,35,2,98,...,98,98,98,98,98,98,2,1,97,0
250833,0b1933,2,1,10-06-2020,06-06-2020,9999-99-99,2,26,1,98,...,98,98,98,98,98,98,1,2,97,0
524581,16ea2c,1,1,25-06-2020,19-06-2020,9999-99-99,2,83,2,98,...,98,98,98,98,98,98,2,3,97,0
518760,0cf8b2,1,1,25-06-2020,19-06-2020,9999-99-99,2,85,2,98,...,98,98,98,98,98,98,2,3,97,0
384532,1aa3ee,2,1,19-06-2020,10-06-2020,9999-99-99,2,26,1,98,...,98,98,98,98,98,98,99,2,97,0

(1842, 23)

Missing values of this feature, also has a small amount in comparison with number of data values. So I'm just going to delete the rows that does not have a proper value.

In [538]:
data_02.drop(invalid_diabetes.index, inplace=True)
data_02['diabetes'].unique()

array([2, 1], dtype=int64)

In [539]:
data_02.shape

(563162, 23)

In [540]:
# the value 98 is not valid for this column
invalid_copd = data_02[(data_02['copd'] != 1) & (data_02['copd'] != 2)]
display(invalid_copd.sample(10))
invalid_copd.shape

,id,sex,patient_type,entry_date,date_symptoms,date_died,pneumonia,age,pregnancy,diabetes,...,hypertension,other_disease,cardiovascular,obesity,renal_chronic,tobacco,contact_other_covid,covid_res,icu,dead
218029,0a0072,2,1,21-04-2020,18-04-2020,9999-99-99,2,42,1,2,...,98,98,98,98,98,98,99,1,97,0
74049,13fb1c,2,2,21-05-2020,12-05-2020,26-05-2020,1,64,1,1,...,1,98,98,1,2,1,99,1,2,1
305294,0483b7,2,1,28-05-2020,25-05-2020,9999-99-99,2,21,1,2,...,2,2,2,2,2,2,2,2,97,0
380022,0741ad,1,2,27-04-2020,27-04-2020,28-04-2020,1,65,2,1,...,98,2,98,2,2,98,99,2,2,1
188058,1c14c5,2,2,21-05-2020,20-05-2020,9999-99-99,1,37,1,2,...,2,2,2,2,2,2,2,1,2,0
302416,0e4213,1,1,19-06-2020,17-06-2020,9999-99-99,2,60,2,1,...,1,2,1,2,2,2,1,2,97,0
46929,0a5fcd,2,2,29-04-2020,28-04-2020,9999-99-99,2,79,1,2,...,98,98,2,98,98,2,2,1,2,0
456985,10ee50,2,1,13-04-2020,10-04-2020,9999-99-99,2,37,1,2,...,1,2,1,1,2,2,2,2,97,0
334675,03cd2d,2,2,13-05-2020,12-05-2020,9999-99-99,2,76,1,1,...,1,98,2,2,2,1,99,2,2,0
531337,12fa14,2,1,22-06-2020,19-06-2020,9999-99-99,2,28,1,2,...,98,98,98,98,98,98,1,3,97,0

(179, 23)

In [541]:
data_02.drop(invalid_copd.index, inplace=True)
data_02['copd'].unique()

array([2, 1], dtype=int64)

In [542]:
data_02.shape

(562983, 23)

In [543]:
# the value 98 is not valid for this column
invalid_asthma = data_02[(data_02['asthma'] != 1) & (data_02['asthma'] != 2)]
display(invalid_asthma.sample(10))
invalid_asthma.shape

,id,sex,patient_type,entry_date,date_symptoms,date_died,pneumonia,age,pregnancy,diabetes,...,hypertension,other_disease,cardiovascular,obesity,renal_chronic,tobacco,contact_other_covid,covid_res,icu,dead
181755,1842bf,2,1,19-04-2020,17-04-2020,9999-99-99,2,29,1,2,...,2,2,2,2,2,2,2,1,97,0
384633,18fab0,1,1,12-06-2020,12-06-2020,9999-99-99,2,43,2,2,...,2,2,2,2,2,2,1,2,97,0
82412,61362,2,2,08-06-2020,08-06-2020,9999-99-99,1,62,1,1,...,98,98,98,1,98,2,99,1,2,0
142461,1c492d,2,2,12-06-2020,09-06-2020,15-06-2020,1,46,1,2,...,98,2,2,2,2,2,1,1,1,1
192771,1cca8c,2,1,25-05-2020,18-05-2020,9999-99-99,1,48,1,1,...,98,1,98,98,98,98,1,1,97,0
260657,0348d4,1,1,13-06-2020,12-06-2020,9999-99-99,2,56,2,2,...,2,2,2,2,2,2,1,2,97,0
489583,0471fb,1,1,17-06-2020,11-06-2020,9999-99-99,2,53,2,2,...,2,2,2,2,2,2,1,2,97,0
246872,0bd54b,1,1,27-05-2020,20-05-2020,9999-99-99,2,51,2,2,...,2,2,2,2,2,2,1,2,97,0
446364,02604a,2,1,13-05-2020,10-05-2020,9999-99-99,2,24,1,2,...,98,98,98,98,2,98,2,2,97,0
531149,1475ee,2,1,25-06-2020,24-06-2020,9999-99-99,2,72,1,2,...,2,2,2,2,2,2,2,3,97,0

(87, 23)

In [544]:
data_02.drop(invalid_asthma.index, inplace=True)
data_02['asthma'].unique()

array([2, 1], dtype=int64)

In [545]:
data_02.shape

(562896, 23)

In [546]:
# the value 98 is not valid for this column
invalid_inmsupr = data_02[(data_02['inmsupr'] != 1) & (data_02['inmsupr'] != 2)]
display(invalid_inmsupr.sample(10))
invalid_inmsupr.shape

,id,sex,patient_type,entry_date,date_symptoms,date_died,pneumonia,age,pregnancy,diabetes,...,hypertension,other_disease,cardiovascular,obesity,renal_chronic,tobacco,contact_other_covid,covid_res,icu,dead
378644,173eca,2,1,03-05-2020,03-05-2020,9999-99-99,2,25,1,2,...,2,98,2,2,2,2,99,2,97,0
445625,0b2d7b,2,1,09-06-2020,03-06-2020,9999-99-99,2,32,1,1,...,2,2,2,1,2,2,2,2,97,0
382566,000b6f,2,2,06-05-2020,30-04-2020,9999-99-99,1,42,1,2,...,1,2,98,2,98,98,99,2,2,0
346687,1.71E+86,2,1,03-06-2020,30-05-2020,9999-99-99,2,66,1,2,...,2,98,2,2,2,2,1,2,97,0
274818,07d667,2,1,21-05-2020,15-05-2020,9999-99-99,2,46,1,2,...,2,98,2,1,2,2,1,2,97,0
151410,03a1ba,2,2,26-05-2020,21-05-2020,16-06-2020,1,65,1,2,...,1,98,2,2,2,2,99,1,2,1
450935,0dc03f,1,1,21-05-2020,18-05-2020,9999-99-99,2,52,2,1,...,2,2,2,2,2,2,1,2,97,0
15993,12fdfd,2,1,08-06-2020,05-06-2020,9999-99-99,2,54,1,2,...,2,2,2,1,2,2,2,1,97,0
132870,0c8107,2,1,18-06-2020,16-06-2020,9999-99-99,2,37,1,1,...,2,98,2,2,2,2,1,1,97,0
151742,1251d7,2,2,28-05-2020,20-05-2020,9999-99-99,1,50,1,1,...,98,2,2,1,2,1,2,1,2,0

(290, 23)

In [547]:
data_02.drop(invalid_inmsupr.index, inplace=True)
data_02['inmsupr'].unique()

array([2, 1], dtype=int64)

In [548]:
data_02.shape

(562606, 23)

In [549]:
# the value 98 is not valid for this column
invalid_hypertension = data_02[(data_02['hypertension'] != 1) & (data_02['hypertension'] != 2)]
display(invalid_hypertension.sample(10))
invalid_hypertension.shape

,id,sex,patient_type,entry_date,date_symptoms,date_died,pneumonia,age,pregnancy,diabetes,...,hypertension,other_disease,cardiovascular,obesity,renal_chronic,tobacco,contact_other_covid,covid_res,icu,dead
417536,15fe0f,1,2,16-05-2020,08-05-2020,9999-99-99,1,47,2,2,...,98,2,2,2,2,2,2,2,2,0
472062,1211b3,2,1,29-05-2020,29-05-2020,9999-99-99,1,74,1,1,...,98,2,1,1,2,2,99,2,97,0
80321,02f0fa,2,1,05-06-2020,29-05-2020,9999-99-99,2,39,1,2,...,98,98,98,98,2,2,1,1,97,0
152109,1808dd,2,1,04-05-2020,30-04-2020,9999-99-99,2,28,1,2,...,98,2,2,2,2,2,2,1,97,0
96577,7.70E+08,2,1,25-05-2020,20-05-2020,9999-99-99,2,47,1,1,...,98,2,98,1,2,2,2,1,97,0
301127,1716f9,1,1,07-06-2020,01-06-2020,9999-99-99,2,39,2,2,...,98,2,2,2,2,2,1,2,97,0
564398,19-Dec-01,2,1,18-06-2020,18-06-2020,9999-99-99,2,33,1,2,...,98,2,2,98,2,2,1,3,97,0
153472,101403,2,1,22-06-2020,21-06-2020,9999-99-99,2,38,1,2,...,98,2,2,2,2,2,1,1,97,0
407105,09b293,1,2,16-06-2020,13-06-2020,9999-99-99,1,21,2,2,...,98,2,2,2,2,2,2,2,2,0
306352,096ebb,1,1,08-06-2020,08-06-2020,9999-99-99,2,49,2,2,...,98,2,2,1,2,2,1,2,97,0

(105, 23)

In [550]:
data_02.drop(invalid_hypertension.index, inplace=True)
data_02['hypertension'].unique()

array([2, 1], dtype=int64)

In [551]:
data_02.shape

(562501, 23)

In [552]:
# the value 98 is not valid for this column
invalid_other_disease = data_02[(data_02['other_disease'] != 1) & (data_02['other_disease'] != 2)]
display(invalid_other_disease.sample(10))
invalid_other_disease.shape

,id,sex,patient_type,entry_date,date_symptoms,date_died,pneumonia,age,pregnancy,diabetes,...,hypertension,other_disease,cardiovascular,obesity,renal_chronic,tobacco,contact_other_covid,covid_res,icu,dead
180624,13ef3b,2,2,16-05-2020,14-05-2020,21-05-2020,1,65,1,2,...,2,98,2,1,2,2,2,1,2,1
52024,11953e,1,2,14-05-2020,06-05-2020,14-05-2020,1,62,2,2,...,2,98,2,1,2,2,2,1,1,1
280100,176a7f,1,1,10-06-2020,10-06-2020,9999-99-99,2,45,2,2,...,2,98,2,2,2,2,1,2,97,0
377156,0c0645,1,2,25-04-2020,20-04-2020,9999-99-99,1,57,2,2,...,1,98,2,1,2,2,2,2,2,0
209862,108419,1,1,23-06-2020,16-06-2020,9999-99-99,2,55,2,1,...,2,98,2,1,2,2,1,1,97,0
142807,90280,1,2,13-06-2020,02-06-2020,9999-99-99,1,33,2,2,...,2,98,98,1,98,2,2,1,2,0
530310,0bd366,2,1,25-05-2020,20-05-2020,28-05-2020,2,51,1,2,...,2,98,2,1,2,2,2,3,97,1
407634,115a08,2,2,20-05-2020,17-05-2020,9999-99-99,1,76,1,2,...,1,98,1,2,2,1,99,2,2,0
114409,1334b9,2,1,08-06-2020,05-06-2020,9999-99-99,2,31,1,2,...,2,98,2,2,2,2,2,1,97,0
80213,0ca412,1,2,03-06-2020,31-05-2020,9999-99-99,1,62,2,2,...,2,98,2,2,2,2,1,1,2,0

(706, 23)

In [553]:
data_02.drop(invalid_other_disease.index, inplace=True)
data_02['other_disease'].unique()

array([2, 1], dtype=int64)

In [554]:
data_02.shape

(561795, 23)

In [555]:
# the value 98 is not valid for this column
invalid_cardiovascular = data_02[(data_02['cardiovascular'] != 1) & (data_02['cardiovascular'] != 2)]
display(invalid_cardiovascular.sample(10))
invalid_cardiovascular.shape

,id,sex,patient_type,entry_date,date_symptoms,date_died,pneumonia,age,pregnancy,diabetes,...,hypertension,other_disease,cardiovascular,obesity,renal_chronic,tobacco,contact_other_covid,covid_res,icu,dead
64195,137d32,2,1,23-06-2020,18-06-2020,9999-99-99,2,13,1,2,...,2,2,98,2,2,2,2,1,97,0
176867,55897,2,2,26-04-2020,24-04-2020,9999-99-99,2,30,1,2,...,2,2,98,98,98,98,2,1,2,0
557512,042d9c,1,2,23-05-2020,21-05-2020,23-05-2020,2,58,2,1,...,1,2,98,2,2,1,2,3,2,1
146154,0fba47,2,2,03-05-2020,27-04-2020,9999-99-99,2,64,1,2,...,2,2,98,2,2,2,2,1,2,0
556312,3564,1,1,11-06-2020,03-06-2020,9999-99-99,2,43,2,2,...,2,1,98,2,2,2,2,3,97,0
77997,17e59b,2,2,04-06-2020,29-05-2020,9999-99-99,1,61,1,1,...,1,2,98,1,98,2,1,1,1,0
406019,19c0a1,2,2,09-05-2020,29-04-2020,9999-99-99,1,60,1,1,...,2,2,98,2,2,1,99,2,2,0
64412,1a2934,2,1,10-05-2020,08-05-2020,25-05-2020,2,44,1,2,...,1,2,98,1,2,1,99,1,97,1
83052,182fd6,1,2,30-05-2020,30-05-2020,9999-99-99,2,58,2,2,...,1,2,98,98,1,1,2,1,2,0
279128,3.10E+75,1,1,19-06-2020,19-06-2020,9999-99-99,2,33,2,2,...,2,2,98,2,2,2,2,2,97,0

(69, 23)

In [556]:
data_02.drop(invalid_cardiovascular.index, inplace=True)
data_02['cardiovascular'].unique()

array([2, 1], dtype=int64)

In [557]:
data_02.shape

(561726, 23)

In [558]:
# the value 98 is not valid for this column
invalid_obesity = data_02[(data_02['obesity'] != 1) & (data_02['obesity'] != 2)]
display(invalid_obesity.sample(10))
invalid_obesity.shape

,id,sex,patient_type,entry_date,date_symptoms,date_died,pneumonia,age,pregnancy,diabetes,...,hypertension,other_disease,cardiovascular,obesity,renal_chronic,tobacco,contact_other_covid,covid_res,icu,dead
110017,51981,2,2,24-05-2020,10-05-2020,25-05-2020,1,60,1,2,...,2,2,2,98,2,2,99,1,2,1
67478,1d0cf1,2,1,16-06-2020,09-06-2020,9999-99-99,2,76,1,1,...,1,2,1,98,2,2,2,1,97,0
215410,1bc4bf,2,1,08-06-2020,03-06-2020,9999-99-99,2,35,1,2,...,2,2,2,98,2,1,1,1,97,0
56395,0a6777,1,2,03-05-2020,25-04-2020,9999-99-99,1,72,2,1,...,2,2,2,98,2,2,99,1,2,0
53737,0e9c4c,2,2,10-05-2020,03-05-2020,11-05-2020,1,59,1,2,...,1,2,2,98,2,2,99,1,2,1
15976,171586,1,1,06-05-2020,06-05-2020,9999-99-99,2,35,2,2,...,2,2,1,98,2,2,1,1,97,0
104673,1ad416,1,2,10-06-2020,09-06-2020,10-06-2020,1,46,2,1,...,2,2,2,98,2,2,99,1,1,1
43120,147a61,2,2,03-05-2020,02-05-2020,10-05-2020,1,48,1,2,...,2,2,2,98,2,2,99,1,2,1
102500,04397d,2,2,01-05-2020,24-04-2020,9999-99-99,1,51,1,1,...,2,2,2,98,2,2,99,1,2,0
197438,16675,1,2,15-05-2020,10-05-2020,19-05-2020,1,66,2,2,...,1,2,2,98,2,2,1,1,1,1

(203, 23)

In [559]:
data_02.drop(invalid_obesity.index, inplace=True)
data_02['obesity'].unique()

array([2, 1], dtype=int64)

In [560]:
data_02.shape

(561523, 23)

In [561]:
# the value 98 is not valid for this column
invalid_renal_chronic = data_02[(data_02['renal_chronic'] != 1) & (data_02['renal_chronic'] != 2)]
display(invalid_renal_chronic.sample(10))
invalid_renal_chronic.shape

,id,sex,patient_type,entry_date,date_symptoms,date_died,pneumonia,age,pregnancy,diabetes,...,hypertension,other_disease,cardiovascular,obesity,renal_chronic,tobacco,contact_other_covid,covid_res,icu,dead
204405,0a55c2,2,1,12-05-2020,12-05-2020,9999-99-99,2,53,1,2,...,2,2,2,1,98,98,2,1,97,0
200175,07a020,1,2,18-05-2020,18-05-2020,28-05-2020,2,48,2,1,...,2,2,2,1,98,2,99,1,1,1
363363,19855e,2,1,17-04-2020,13-04-2020,9999-99-99,2,36,1,2,...,2,2,2,2,98,1,1,2,97,0
190133,119a57,2,1,17-06-2020,07-06-2020,9999-99-99,2,50,1,2,...,2,1,2,2,98,1,1,1,97,0
528938,09039c,2,1,29-06-2020,16-06-2020,9999-99-99,2,27,1,2,...,2,2,2,1,98,2,2,3,97,0
411794,0970dc,1,2,07-06-2020,05-06-2020,07-06-2020,1,48,2,1,...,1,2,2,1,98,2,99,2,1,1
382034,0b248c,1,1,12-06-2020,09-06-2020,9999-99-99,2,51,2,1,...,2,1,2,2,98,2,1,2,97,0
460460,16298,1,2,13-05-2020,06-05-2020,9999-99-99,1,71,2,1,...,2,2,2,1,98,2,99,2,2,0
103140,0e0364,2,2,27-04-2020,20-04-2020,9999-99-99,2,67,1,1,...,1,2,2,2,98,2,2,1,2,0
246300,06e35c,2,2,23-05-2020,20-05-2020,9999-99-99,1,97,1,2,...,1,1,2,2,98,2,99,2,2,0

(88, 23)

In [562]:
data_02.drop(invalid_renal_chronic.index, inplace=True)
data_02['renal_chronic'].unique()

array([2, 1], dtype=int64)

In [563]:
data_02.shape

(561435, 23)

In [564]:
# the value 98 is not valid for this column
invalid_tobacco = data_02[(data_02['tobacco'] != 1) & (data_02['tobacco'] != 2)]
display(invalid_tobacco.sample(10))
invalid_tobacco.shape

,id,sex,patient_type,entry_date,date_symptoms,date_died,pneumonia,age,pregnancy,diabetes,...,hypertension,other_disease,cardiovascular,obesity,renal_chronic,tobacco,contact_other_covid,covid_res,icu,dead
174747,01eeac,2,1,03-06-2020,30-05-2020,9999-99-99,2,47,1,1,...,2,2,2,1,2,98,1,1,97,0
51309,0e2258,2,1,18-06-2020,12-06-2020,9999-99-99,2,45,1,2,...,2,2,2,1,2,98,1,1,97,0
196901,5.40E+02,2,1,01-06-2020,28-05-2020,9999-99-99,2,52,1,2,...,2,2,2,1,2,98,1,1,97,0
529159,01954c,1,2,26-06-2020,21-06-2020,9999-99-99,1,58,2,2,...,2,2,2,1,2,98,99,3,2,0
9298,073fcd,2,1,20-05-2020,18-05-2020,9999-99-99,2,33,1,2,...,2,2,2,2,2,98,2,1,97,0
466389,125ac9,2,1,05-06-2020,29-05-2020,9999-99-99,2,43,1,2,...,2,2,2,2,2,98,1,2,97,0
195871,078c39,1,2,13-05-2020,10-05-2020,9999-99-99,1,59,2,1,...,1,2,1,2,2,98,2,1,2,0
467764,0bdc27,2,1,13-06-2020,11-06-2020,9999-99-99,2,40,1,2,...,2,2,2,2,1,98,1,2,97,0
469421,19b1bc,2,1,18-05-2020,15-05-2020,9999-99-99,2,41,1,1,...,2,2,2,1,2,98,1,2,97,0
413785,1ae035,2,1,17-06-2020,16-06-2020,9999-99-99,2,55,1,2,...,2,2,2,1,2,98,1,2,97,0

(217, 23)

In [565]:
data_02.drop(invalid_tobacco.index, inplace=True)
data_02['tobacco'].unique()

array([2, 1], dtype=int64)

In [566]:
data_02.shape

(561218, 23)

In [567]:
# the value 99 is not valid for this column
invalid_contact_other_covid = data_02[(data_02['contact_other_covid'] != 1) & (data_02['contact_other_covid'] != 2)]
display(invalid_contact_other_covid.sample(10))
invalid_contact_other_covid.shape

,id,sex,patient_type,entry_date,date_symptoms,date_died,pneumonia,age,pregnancy,diabetes,...,hypertension,other_disease,cardiovascular,obesity,renal_chronic,tobacco,contact_other_covid,covid_res,icu,dead
49227,0f5581,2,1,13-06-2020,06-06-2020,9999-99-99,2,54,1,2,...,2,2,2,1,2,2,99,1,97,0
76972,1845b5,2,2,22-04-2020,22-04-2020,08-05-2020,1,80,1,2,...,2,2,2,2,2,2,99,1,2,1
339895,0f1350,2,1,28-05-2020,27-05-2020,9999-99-99,2,49,1,1,...,1,2,2,2,2,2,99,2,97,0
532005,0307f7,2,1,22-06-2020,22-06-2020,9999-99-99,2,48,1,1,...,1,2,2,2,2,2,99,3,97,0
279165,0e7df8,1,1,23-04-2020,17-04-2020,9999-99-99,2,48,2,2,...,2,2,2,2,2,2,99,2,97,0
155064,14934f,2,2,25-05-2020,22-05-2020,9999-99-99,1,55,1,2,...,1,2,2,2,2,2,99,1,2,0
543518,03c10f,1,1,25-06-2020,16-06-2020,9999-99-99,2,57,2,2,...,2,2,2,1,2,2,99,3,97,0
166150,119f39,1,2,19-04-2020,19-04-2020,22-04-2020,1,63,2,1,...,1,1,1,2,2,2,99,1,2,1
342637,9417,2,1,12-05-2020,11-05-2020,9999-99-99,2,6,1,2,...,2,2,2,2,2,2,99,2,97,0
17636,011cec,2,1,26-05-2020,21-05-2020,9999-99-99,2,42,1,2,...,2,2,2,2,2,2,99,1,97,0

(173550, 23)

In [568]:
print(invalid_contact_other_covid[invalid_contact_other_covid['contact_other_covid'] == 99]['patient_type'].unique())
print(invalid_contact_other_covid[invalid_contact_other_covid['contact_other_covid'] == 99]['sex'].unique())

[1 2]
[2 1]

In this case there's a lot of data missing. Also it seems like it's something effective in the output?????

In [569]:
data_02.drop(invalid_contact_other_covid.index, inplace=True)

In [570]:
invalid_covid_res = data_02[data_02['covid_res'] == 3]
invalid_covid_res.shape[0]

44973

In [571]:
data_02.drop(invalid_covid_res.index, inplace=True)

In [572]:
data_02['icu'].unique()

array([97,  2,  1, 99], dtype=int64)

In [573]:
# the values 97 and 99 are not valid for this column
invalid_icu = data_02[(data_02['icu'] != 1) & (data_02['icu'] != 2)]
display(invalid_icu.sample(10))
invalid_icu.shape

,id,sex,patient_type,entry_date,date_symptoms,date_died,pneumonia,age,pregnancy,diabetes,...,hypertension,other_disease,cardiovascular,obesity,renal_chronic,tobacco,contact_other_covid,covid_res,icu,dead
455063,182df0,2,1,13-04-2020,09-04-2020,9999-99-99,2,31,1,2,...,2,2,2,2,2,2,2,2,97,0
330130,14ca83,2,1,15-06-2020,09-06-2020,9999-99-99,2,38,1,2,...,2,2,2,2,2,2,2,2,97,0
385326,0ce078,1,1,18-06-2020,12-06-2020,9999-99-99,2,52,2,2,...,1,2,2,1,2,2,2,2,97,0
176441,0ec32c,1,1,11-05-2020,10-05-2020,12-05-2020,1,46,2,1,...,1,2,2,2,1,2,2,1,97,1
425976,0032d9,2,1,30-04-2020,27-04-2020,9999-99-99,2,35,1,2,...,2,2,2,2,2,2,1,2,97,0
294523,10b958,1,1,25-06-2020,20-06-2020,9999-99-99,2,25,2,2,...,2,2,2,2,2,2,1,2,97,0
390881,01cd5a,2,1,01-05-2020,30-04-2020,9999-99-99,2,22,1,2,...,2,2,2,2,2,2,2,2,97,0
75353,0fe5f2,2,1,01-06-2020,27-05-2020,9999-99-99,2,47,1,2,...,1,2,2,2,2,2,1,1,97,0
269604,0cfabd,2,1,23-06-2020,22-06-2020,9999-99-99,2,36,1,2,...,2,2,2,2,2,2,1,2,97,0
23530,134496,1,1,22-04-2020,09-04-2020,9999-99-99,2,66,2,1,...,2,1,2,2,2,2,2,1,97,0

(291016, 23)

In [574]:
print(invalid_icu[invalid_icu['icu'] == 97]['patient_type'].unique())
print(invalid_icu[invalid_icu['icu'] == 99]['patient_type'].unique())

[1]
[2]

In [575]:
data_02['icu'].replace(99, 2, inplace=True)
print(data_02.icu.unique())

data_02.loc[data_02['icu'] == 97].shape[0]

[97  2  1]

290925

Like intubed feature, icu also has a lot of missing values that can't be ignored or corrected. So I'm going to delete this feature too.

In [576]:
data_02.drop('icu', axis='columns', inplace=True)

In [577]:
data.shape

(566602, 23)

In [578]:
data_02.shape

(342695, 22)

In [579]:
print(data_02.date_symptoms.dtypes)

object

In [580]:
data_02[['entry_date','date_symptoms']] = data_02[['entry_date','date_symptoms']].apply(pd.to_datetime, dayfirst=True, errors='coerce')

In [581]:
data_02['symptoms_to_entry'] = (data_02['entry_date'] - data_02['date_symptoms']) // np.timedelta64(1, 'D')

In [582]:
data_02.head()

,id,sex,patient_type,entry_date,date_symptoms,date_died,pneumonia,age,pregnancy,diabetes,...,hypertension,other_disease,cardiovascular,obesity,renal_chronic,tobacco,contact_other_covid,covid_res,dead,symptoms_to_entry
0,16169f,2,1,2020-05-04,2020-05-02,9999-99-99,2,27,1,2,...,2,2,2,2,2,2,2,1,0,2
7,0ce1f5,1,1,2020-05-21,2020-05-18,9999-99-99,2,56,2,2,...,1,2,2,2,1,1,1,1,0,3
13,11c741,1,1,2020-05-25,2020-05-23,9999-99-99,2,34,2,2,...,2,2,2,2,2,2,1,1,0,2
15,194bf2,1,1,2020-06-20,2020-06-16,9999-99-99,2,34,2,2,...,2,2,2,2,2,1,2,1,0,4
16,158eef,1,1,2020-06-24,2020-06-15,9999-99-99,2,49,2,1,...,2,2,2,2,2,2,1,1,0,9

In [583]:
# data_02['date_died'] = pd.to_datetime(data_02['date_died'], dayfirst=True, errors='coerce')
# # display(data_02.sample(5))
# # print(data_02.date_died.unique())

# valid_date_died = data_02['date_died'].notna()

# data_02['entry_to_dead'] = (data_02.loc[valid_date_died.index, 'date_died'] - data_02.loc[valid_date_died.index, 'entry_date']) / np.timedelta64(1, 'D')

# print(data_02.loc[data_02['dead'] == 0].shape[0])
# data_02['entry_to_dead'].isna().sum()

In [584]:
data_02.drop(['entry_date', 'date_symptoms', 'date_died'], axis='columns', inplace=True)

In [585]:
data_02

,id,sex,patient_type,pneumonia,age,pregnancy,diabetes,copd,asthma,inmsupr,hypertension,other_disease,cardiovascular,obesity,renal_chronic,tobacco,contact_other_covid,covid_res,dead,symptoms_to_entry
0,16169f,2,1,2,27,1,2,2,2,2,2,2,2,2,2,2,2,1,0,2
7,0ce1f5,1,1,2,56,2,2,2,2,2,1,2,2,2,1,1,1,1,0,3
13,11c741,1,1,2,34,2,2,2,2,2,2,2,2,2,2,2,1,1,0,2
15,194bf2,1,1,2,34,2,2,2,2,2,2,2,2,2,2,1,2,1,0,4
16,158eef,1,1,2,49,2,1,2,2,2,2,2,2,2,2,2,1,1,0,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499686,0acdb8,1,1,2,15,2,2,2,2,2,2,2,2,2,2,2,1,2,0,11
499687,1342ee,2,1,1,77,1,2,2,2,2,2,1,2,2,2,1,2,2,0,6
499688,0186c8,2,2,1,63,1,2,2,2,2,1,2,2,1,2,1,2,2,0,5
499689,130373,1,1,2,25,2,2,2,2,2,2,2,2,2,2,2,2,2,0,3
499690,10b265,1,1,2,45,2,2,2,2,2,1,2,2,2,2,2,1,2,0,2

In [586]:
for column in data_02.columns:
    print(f'{column} unique values: {data_02[column].unique()}\n-------------------------------------------')

id unique values: ['16169f' '0ce1f5' '11c741' ... '0186c8' '130373' '10b265']
-------------------------------------------
sex unique values: [2 1]
-------------------------------------------
patient_type unique values: [1 2]
-------------------------------------------
pneumonia unique values: [2 1]
-------------------------------------------
age unique values: [ 27  56  34  49  54  25  61  40  52  53  57  51  45  67  78  79  59  44
  31  33  58  48  29  35  38  36  80  71  39  26  46  55  32  76  66  24
  43  63  17  37  42  60  65  30  50  73  41  47  20  23  28  84  69  62
  68  64  92  72  90  70   7  19  82   0  22  21  74   4  83  87  81  18
   9   8  93  15  14  11   1  88  13  75  95  77  16  85  91  89  86  10
  12   3   5   6   2  98  97  96  94 100 119 101  99 103 114 106 102 116
 120 104 118 109 110 117 115 113 108 107 111]
-------------------------------------------
pregnancy unique values: [1 2]
-------------------------------------------
diabetes unique values: [2 1]
-------------------------------------------
copd unique values: [2 1]
-------------------------------------------
asthma unique values: [2 1]
-------------------------------------------
inmsupr unique values: [2 1]
-------------------------------------------
hypertension unique values: [2 1]
-------------------------------------------
other_disease unique values: [2 1]
-------------------------------------------
cardiovascular unique values: [2 1]
-------------------------------------------
obesity unique values: [2 1]
-------------------------------------------
renal_chronic unique values: [2 1]
-------------------------------------------
tobacco unique values: [2 1]
-------------------------------------------
contact_other_covid unique values: [2 1]
-------------------------------------------
covid_res unique values: [1 2]
-------------------------------------------
dead unique values: [0 1]
-------------------------------------------
symptoms_to_entry unique values: [ 2  3  4  9  0  1  5  6 10 12  7 15 13 14 11  8 23 16 33 35 17 20 18 32
 25 19 22 34 38 21 29 28 30 48 31 63 27 62 53 37 89 36 59 24 41 40 51 60]
-------------------------------------------

# Imbalanced data

In [587]:
# the number of labels that are equal to 1
died_data = data_02[data_02['dead'] == 1]
size1 = died_data.shape
size1

(13059, 20)

In [662]:
# the number of labels that are equal to 0
survived_data = data_02[data_02['dead'] == 0]
size2 = survived_data.shape
size2

(329636, 20)

In [663]:
size2[0] / size1[0]

25.24205528754116

This dataset is known as an imbalanced dataset; Because number of class samples are drastically different. This cause the model to predict that one label which has a larger sample(in our case, number of people who have survived are much more than people who have died) more often.

# Separating Train and Test set

In [590]:
data_train = data_02.sample(frac = 0.8)
data_train.head()

,id,sex,patient_type,pneumonia,age,pregnancy,diabetes,copd,asthma,inmsupr,hypertension,other_disease,cardiovascular,obesity,renal_chronic,tobacco,contact_other_covid,covid_res,dead,symptoms_to_entry
367293,0bc8cc,1,1,2,33,2,2,2,2,2,2,2,2,2,2,2,1,2,0,0
418969,07480b,2,1,2,41,1,2,2,2,2,2,2,2,2,2,2,1,2,0,0
120261,02c2fa,2,1,2,49,1,2,2,2,2,2,2,2,2,2,2,2,1,0,6
188963,0a5c4e,2,1,2,45,1,2,2,2,2,2,2,2,2,2,2,1,1,0,6
105441,14cb6d,2,1,2,66,1,2,2,2,2,2,2,2,2,2,2,1,1,1,12

In [591]:
data_test = data_02.drop(data_train.index)
data_test.head()

,id,sex,patient_type,pneumonia,age,pregnancy,diabetes,copd,asthma,inmsupr,hypertension,other_disease,cardiovascular,obesity,renal_chronic,tobacco,contact_other_covid,covid_res,dead,symptoms_to_entry
15,194bf2,1,1,2,34,2,2,2,2,2,2,2,2,2,2,1,2,1,0,4
39,057a3b,2,1,1,56,1,2,2,2,2,2,2,2,2,2,2,2,1,0,6
58,097d14,2,1,2,27,1,2,2,2,2,2,2,2,2,2,2,1,1,0,0
74,0a138a,1,1,1,45,2,2,2,2,2,2,2,2,2,2,2,1,1,0,2
116,0b23eb,2,1,2,48,1,2,2,2,2,2,2,2,2,2,2,2,1,0,2

In [592]:
# features' indexes
idx = np.arange(20)
idx = np.delete(idx, [0, 19])
idx

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [593]:
data_train.columns.size

20

In [594]:
x_train = data_train.iloc[:, idx].values
y_train = data_train['dead'].values

In [595]:
x_test0 = data_test.loc[data_test.dead == 0, data_test.columns[idx]].values
x_test1 = data_test.loc[data_test.dead == 1, data_test.columns[idx]].values
y_test0 = data_test.loc[data_test.dead == 0, 'dead'].values
y_test1 = data_test.loc[data_test.dead == 1, 'dead'].values

In [596]:
print(x_test0.shape)
print(x_test1.shape)
print(y_test0.shape)
print(y_test1.shape)

(65900, 18)
(2639, 18)
(65900,)
(2639,)

# Creating our model

In [597]:
def sigmoid(Z):
    g = 1 / (1 + np.exp(-Z))
    return g

In [598]:
def compute_cost(W, b, x, y):
    m = x.shape[0]
    Z = np.dot(x, W.T) + b
    epsilon = 1e-15
    g = np.clip(sigmoid(Z), epsilon, 1 - epsilon) 
    J = (y * np.log(g)) + ((1 - y) * np.log(1 - g))
    j = J.sum()
    j = j / (-m)
    return j

In [599]:
W = np.ones(18)
b = 0
compute_cost(W, b, x_train, y_train)

33.17414151985348

In [600]:
def compute_gradient(W, b, x, y):
    m = len(x)
    Z = np.dot(x, W.T) + b
    g = sigmoid(Z)
    error = g - y
    
    d_W = np.dot(x.T, error) / m
    d_b = error.sum() / m
    
    return d_W, d_b

In [601]:
W = np.ones(18)
b = 0
compute_gradient(W, b, x_train, y_train)

(array([ 1.44581187e+00,  1.07902800e+00,  1.82939275e+00,  3.91388115e+01,
         1.43331169e+00,  1.83157399e+00,  1.91307869e+00,  1.89436671e+00,
         1.91223245e+00,  1.80022688e+00,  1.90935088e+00,  1.90640730e+00,
         1.77533229e+00,  1.91215950e+00,  1.84010563e+00,  1.36374911e+00,
         1.55261603e+00, -1.03309995e-15]),
 0.9619924422591487)

In [602]:
def gradient_descent(W_0, b_0, x, y, num_iter, alpha):
    W = W_0
    b = b_0
    
    m = len(x)
    cost_history = []
    for i in range(num_iter):
        d_W, d_b = compute_gradient(W, b, x, y)
        
        W = W - alpha * d_W
        b = b - alpha * d_b
        
        cost = compute_cost(W, b, x, y)
        cost_history.append(cost)
        
        if i % 100 == 0:
            print(f'cost at iteration {i} is {cost:.4f}')
            
    return W, b, cost_history

In [603]:
W_0 = np.ones(18)
b_0 = 0
num_iter = 1000
alpha = 0.01
W_opt, b_opt, cost_history = gradient_descent(W_0, b_0, x_train, y_train, num_iter, alpha)

cost at iteration 0 is 33.1397
cost at iteration 100 is 1.9205
cost at iteration 200 is 1.5694
cost at iteration 300 is 1.1414
cost at iteration 400 is 0.7125
cost at iteration 500 is 0.3563
cost at iteration 600 is 0.1707
cost at iteration 700 is 0.1157
cost at iteration 800 is 0.0963
cost at iteration 900 is 0.0869

# Performance Evaluation and Analysis

In [604]:
def y_pred(W, b, x, threshold):
    Z = np.dot(x, W.T) + b
    g = sigmoid(Z)

    y_hat = np.where(g >= threshold, 1, 0)
    return y_hat

## Confusion Matrix

In [657]:
def compute_metrics(y_true, y_pred):
    TP = np.sum((y_true == 1) & (y_pred == 1))
    # print(TP)
    FP = np.sum((y_true == 0) & (y_pred == 1))
    # print(FP)
    FN = np.sum((y_true == 1) & (y_pred == 0))
    # print(FN)
    TN = np.sum((y_true == 0) & (y_pred == 0))
    # print(TN)
    
    accuracy = (TP + TN) / len(y_true)
    precision = TP / (TP + FP) if (TP + FP) != 0 else 0
    recall = TP / (TP + FN) if (TP + FN) != 0 else 0
    f1_score = 2 * (precision * recall) / (precision + recall) if (precision + recall) != 0 else 0
    
    metrics = {
        "Accuracy": accuracy,
        "Precision": precision,
        "Recall": recall,
        "F1-Score": f1_score
    }
    
    return metrics

In [659]:
prediction = y_pred(W_opt, b_opt, x_train, 0.5)
metrics = compute_metrics(y_train, prediction)
for metric, value in metrics.items():
    print(f"{metric}: {value:.2f}")

105
0
10315
263736
Accuracy: 0.96
Precision: 1.00
Recall: 0.01
F1-Score: 0.02

In [660]:
prediction = y_pred(W_opt, b_opt, x_test0, 0.5)
metrics = compute_metrics(y_test0, prediction)
for metric, value in metrics.items():
    print(f"{metric}: {value:.2f}")

0
0
0
65900
Accuracy: 1.00
Precision: 0.00
Recall: 0.00
F1-Score: 0.00

In [661]:
prediction = y_pred(W_opt, b_opt, x_test1, 0.5)
metrics = compute_metrics(y_test1, prediction)
for metric, value in metrics.items():
    print(f"{metric}: {value:.2f}")

43
0
2596
0
Accuracy: 0.02
Precision: 1.00
Recall: 0.02
F1-Score: 0.03

<p dir='rtl'> معیار accuracy برای دیتاست مورد نظر گزینه مناسبی نیست؛ چراکه دیتاست نامتوازن است. بدین معنا که نمونه های کلاس ها تعداد برابری نیستند. در این حالت با وجود اینکه مدل ما از accuracy بالایی برخوردار است، قادر به پیش بینی کلاس <code>dead=1</code> نیست. برای تحلیل بهتر میتوانیم از <code>recall, F1-score</code> استفاده کنیم.</p>
<br>
<p dir='rtl'><code>reacall</code> برابر نسبت تعداد حالت هایی است که مدل موفق به پیش بینی درست<code>dead=1</code> شده است به تعداد کل حالاتی که دیتاست <code>dead=1</code> دارد.</p>
<br>
<p dir='rtl'><code>F1-score</code> معیاری ای مناسب برای تحیلیل مدلی است که دیتاست ان نامتوازن است؛ چرا که اگر هر کدام از مقادیر <code>recall</code> یا <code>precision</code> کوچک باشند، مقدار <code>F1-score</code> نیز کوچک خواهد شد.</p>

In [642]:
def threshold_tuning(W, b, x, y, metric, step):
    threshold_range = np.arange(step, 1, step)
    my_metric = np.zeros_like(threshold_range)
    n = len(threshold_range)
    
    precision = abs(int(np.floor(np.log10(step))))

    
    for i in range(n):
        prediction = y_pred(W, b, x, threshold_range[i])
        metrics = compute_metrics(y, prediction)
        my_metric[i] = metrics[metric]
        
    index = my_metric.argmax()
    best_threshold = threshold_range[index] 
    print(f'best threshold: {best_threshold:.{precision}f}\n{metric}: {my_metric[index]:.4f}')    
    
    return best_threshold

In [643]:
threshold_tuning(W_opt, b_opt, x_train, y_train, 'F1-Score', 0.01)

best threshold: 0.19
F1-Score: 0.9362

0.19

In [644]:
threshold_tuning(W_opt, b_opt, x_train, y_train, "Recall", 0.01)

best threshold: 0.01
Recall: 1.0000

0.01

In [647]:
threshold_tuning(W_opt, b_opt, x_train, y_train, 'Precision', 0.01)

best threshold: 0.38
Precision: 1.0000

0.38

More accurate:

In [648]:
best_threshold = threshold_tuning(W_opt, b_opt, x_train, y_train, 'F1-Score', 0.001)

best threshold: 0.182
F1-Score: 0.9367

## Evaluating with test data

### 'dead' == 0

In [650]:
prediction = y_pred(W_opt, b_opt, x_test0, best_threshold)
metrics = compute_metrics(y_test0, prediction)
for metric, value in metrics.items():
    print(f"{metric}: {value:.2f}")

Accuracy: 1.00
Precision: 0.00
Recall: 0.00
F1-Score: 0.00

### 'dead' == 1

In [652]:
prediction = y_pred(W_opt, b_opt, x_test1, best_threshold)
metrics = compute_metrics(y_test1, prediction)
for metric, value in metrics.items():
    print(f"{metric}: {value:.2f}")

Accuracy: 0.92
Precision: 1.00
Recall: 0.92
F1-Score: 0.96

# Visualization

In [622]:
sample = data_02.sample(frac = 0.1)